### ISSUE TITLE
Not working on ubuntu 15.10 x64

### ISSUE THREAD

**Issue by ghost** [stonewell/exchange-ews-thunderbird#1]
*_Not working *_ on ubuntu 15.10 x64
How i can debug it or see logs?

> Goto menu Options->Account Settings, from the drop down list “Account Actions”, choose “Add Ews Account”, input the email, user name and password, either discover the ews address or input the url directly. Select the authentication method (Office365 should be Basic, other may choose NTLM), the discover button will also try to detect the authentication method.

**Comment by stonewell** [comment]
the current exchange-ews only works for 32bit thunderbird, if you are using
64bit I can build one.

you can find thunderbird error console through Options->Tools->Error
Console.

so what's the "Not Working"? no ews account shows in the Account Actions?
or crash?
Thanks,

Jack Star notifications@github.com于2016年2月24日周三 下午12:05写道：

**Comment by ghost** [comment]
_Not working_ means that when i put all my email credentials and URLs, it shows me only this in Error console

```
TypeError: Cc['@angsto-tech.com/mailews/service;1'] is undefined
chrome://mailews/content/ewsserver.js
String: 22
```

[http://joxi.ru/4AkEJ8oflOXamq]

I tried to choose different type like Basic and NTLM, but when i clicked OK button - nothing is happening.
My version of Thunderbird is 38.5.1

**Comment by stonewell** [comment]
It looks like the addon is not loaded correctly, Can you kindly do checks
below:
1. check if any log related with "ews.so" in the error console
2. check if the thunderbird is 32bit instead of x86_64 version, if get
thunderbird from
ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/38.5.1/linux-x86_64/en-US/thunderbird-38.5.1.tar.bz2,
it is a x86_64 bit version,

if you do want a x86_64 version, I could build one for your test.

Thanks,
Jingnan

Jack Star notifications@github.com于2016年2月25日周四 上午3:06写道：

**Comment by stonewell** [comment]
hi,
I build linux-x86_64 version, could you have a try?

https://github.com/stonewell/exchange-ews-thunderbird/tree/master/bin/linux-x86_64

Thanks,
Jingnan

jingnan si jingnan.si@gmail.com于2016年2月25日周四 下午4:40写道：

**Comment by ghost** [comment]
Still no luck

```
 TypeError: Cc['@angsto-tech.com/mailews/service;1'] is undefined
 chrome://mailews/content/ewsserver.js
 String: 22 
```

**Comment by stonewell** [comment]
Bad to heard that, I will install an ubuntu to verify since I am testing on
a debian.

Jack Star notifications@github.com于2016年3月2日周三 上午7:22写道：

**Comment by ghost** [comment]
In debian sid it autodiscovers the url path, but after click next, thunderbird has crashed. On ubuntu discover button didn`t work at all.

**Comment by stonewell** [comment]
I will upload a new version, since some library linked is not corrrect.
I have tested the new build on Ubuntu 15.10, it should work.
let you know when I finish upload

Jack Star notifications@github.com于2016年3月2日周三 下午2:20写道：

**Comment by stonewell** [comment]
about the crash is there any possible you can send me the core dump file?

jingnan si jingnan.si@gmail.com于2016年3月2日周三 下午2:29写道：

**Comment by stonewell** [comment]
new linux version 1.5.2 uploaded including x86_64 and i686 arch.

Jack Star notifications@github.com于2016年3月2日周三 下午2:20写道：

**Comment by stonewell** [comment]
Hi, is the plugin working for you?
