### ISSUE TITLE
Any chance to see sources

### ISSUE THREAD

**Issue by frenchbeard** [stonewell/exchange-ews-thunderbird#2]
Hi there, just wondering if there would be any way to contribute to these addons in any other way than bug report. They seem to be working rather well so far on Archlinux, except a couple of crashes here and there, but I cannot check where the problem may lie having only debug info, especially regarding interaction with other plugins (among them, muttator is a little... heavy, and may be the cause of such crashes, but no time to see where the problem lies when thunderbird just... well crashes).

**Comment by stonewell** [comment]
Of course, but I am not in town now, I will upload source and let you know when I am done

**Comment by frenchbeard** [comment]
Thanks a lot, and also for the rather impressive work on the plugin.

**Comment by stonewell** [comment]
the source code uploaded, please try and any problem let me known.

-Jingnan

Sébastien Le Corre notifications@github.com于2016年3月9日周三 上午5:32写道：

**Comment by stonewell** [comment]
the source code uploaded, please try and any problem let me known.
